/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MBKRouteImport } from './routes/MBK'
import { Route as HaroonRouteImport } from './routes/haroon'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MBKRoute = MBKRouteImport.update({
  id: '/MBK',
  path: '/MBK',
  getParentRoute: () => rootRouteImport,
} as any)
const HaroonRoute = HaroonRouteImport.update({
  id: '/haroon',
  path: '/haroon',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/MBK': typeof MBKRoute
  '/haroon': typeof HaroonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/MBK': typeof MBKRoute
  '/haroon': typeof HaroonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/MBK': typeof MBKRoute
  '/haroon': typeof HaroonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/MBK' | '/haroon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/MBK' | '/haroon'
  id: '__root__' | '/' | '/MBK' | '/haroon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MBKRoute: typeof MBKRoute
  HaroonRoute: typeof HaroonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MBK': {
      id: '/MBK'
      path: '/MBK'
      fullPath: '/MBK'
      preLoaderRoute: typeof MBKRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haroon': {
      id: '/haroon'
      path: '/haroon'
      fullPath: '/haroon'
      preLoaderRoute: typeof HaroonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MBKRoute: MBKRoute,
  HaroonRoute: HaroonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
